
services:
  # 1. Banco Vetorial (pgvector)
  db_vector:
    image: ankane/pgvector
    container_name: db_vector
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manifold_development
    ports:
      - "5432:5432"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 3. Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 4. Engine Python
  engine_python:
    build: 
      context: ./engine_python
      dockerfile: Dockerfile
    container_name: engine_python
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    volumes:
      - ./engine_python:/app
      - ./shared_data:/app/shared_data
    stdin_open: true
    tty: true
    depends_on:
      - db_vector
      - redis
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 5. Transport Go
  transport_go:
    build: 
      context: ./transport_go
      dockerfile: Dockerfile
    container_name: transport_go
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./shared_data:/app/shared_data
    depends_on:
      - redis
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 6. Envoy Proxy
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy
    volumes:
      - /workspace/infra/envoy:/etc/envoy/config
    command: -c /etc/envoy/config/envoy.yaml 
    ports:
      - "10000:10000"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 7. Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080" 
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/devildev/ESTRUTURA_RESSONANCIA:/workspace
    networks:
      - ressonancia_net
    profiles: ["jenkins"]

  # 8. Aplicação Rails
  manifold_app:
    build: .
    container_name: manifold_app
    environment:
      DB_HOST: db_vector
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: manifold_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
    depends_on:
      - db_vector
      - redis
    networks:
      - ressonancia_net
    ports:
      - "3000:3000"
    profiles: ["pipeline"]

networks:
  ressonancia_net:
    driver: bridge
