
services:
  # 1. O HIPERPLANO (Banco Vetorial - pgvector)
  db_vector:
    image: ankane/pgvector
    container_name: db_vector
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manifold_development
    ports:
      - "5432:5432"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 2. O PULSO (Mensageria RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 3. MEMÓRIA DE CURTO PRAZO (Redis)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ressonancia_net
    profiles: ["pipeline"]

  # 4. O COLISOR (Motor de Geometria da Informação)
  engine_python:
    build: 
      context: ./engine_python
      dockerfile: Dockerfile
    container_name: engine_python
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    volumes:
      - ./engine_python:/app
      - ./shared_data:/app/shared_data
    stdin_open: true
    tty: true
    depends_on:
      - db_vector
      - redis
    networks:
