# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resonance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resonance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fresonance.proto\x12\tresonance\"U\n\x0fRequisicaoSalto\x12\x12\n\ntoken_orto\x18\x01 \x01(\t\x12\x12\n\ntoken_para\x18\x02 \x01(\t\x12\x1a\n\x12\x65letronegatividade\x18\x03 \x01(\x02\"\xb5\x01\n\x0cRespostaZeta\x12\x1a\n\x12probabilidade_zeta\x18\x01 \x01(\x02\x12\x17\n\x0f\x63urvatura_ricci\x18\x02 \x01(\x02\x12\x17\n\x0fresultado_final\x18\x03 \x01(\x02\x12\x17\n\x0f\x65lemento_logico\x18\x04 \x01(\t\x12\x11\n\tspin_fase\x18\x05 \x01(\x02\x12\x12\n\nsh6_coeffs\x18\x06 \x03(\x02\x12\x17\n\x0f\x64\x65nsidade_tempo\x18\x07 \x01(\x02\x32X\n\rAuditoriaZeta\x12G\n\x0e\x43onsultarSalto\x12\x1a.resonance.RequisicaoSalto\x1a\x17.resonance.RespostaZeta\"\x00\x42\x1eZ\x1cmanifold/transport/resonanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resonance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034manifold/transport/resonance'
  _globals['_REQUISICAOSALTO']._serialized_start=30
  _globals['_REQUISICAOSALTO']._serialized_end=115
  _globals['_RESPOSTAZETA']._serialized_start=118
  _globals['_RESPOSTAZETA']._serialized_end=299
  _globals['_AUDITORIAZETA']._serialized_start=301
  _globals['_AUDITORIAZETA']._serialized_end=389
# @@protoc_insertion_point(module_scope)
