# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import resonance_pb2 as resonance__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resonance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditoriaZetaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarSalto = channel.unary_unary(
                '/resonance.AuditoriaZeta/ConsultarSalto',
                request_serializer=resonance__pb2.RequisicaoSalto.SerializeToString,
                response_deserializer=resonance__pb2.RespostaZeta.FromString,
                _registered_method=True)


class AuditoriaZetaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarSalto(self, request, context):
        """O Rails ou o Python consultam o estado da dobra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditoriaZetaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarSalto': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarSalto,
                    request_deserializer=resonance__pb2.RequisicaoSalto.FromString,
                    response_serializer=resonance__pb2.RespostaZeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resonance.AuditoriaZeta', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resonance.AuditoriaZeta', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditoriaZeta(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarSalto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resonance.AuditoriaZeta/ConsultarSalto',
            resonance__pb2.RequisicaoSalto.SerializeToString,
            resonance__pb2.RespostaZeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
