// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: resonance.proto

package resonance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditoriaZeta_ConsultarSalto_FullMethodName = "/resonance.AuditoriaZeta/ConsultarSalto"
)

// AuditoriaZetaClient is the client API for AuditoriaZeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditoriaZetaClient interface {
	// O Rails ou o Python consultam o estado da dobra
	ConsultarSalto(ctx context.Context, in *RequisicaoSalto, opts ...grpc.CallOption) (*RespostaZeta, error)
}

type auditoriaZetaClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditoriaZetaClient(cc grpc.ClientConnInterface) AuditoriaZetaClient {
	return &auditoriaZetaClient{cc}
}

func (c *auditoriaZetaClient) ConsultarSalto(ctx context.Context, in *RequisicaoSalto, opts ...grpc.CallOption) (*RespostaZeta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespostaZeta)
	err := c.cc.Invoke(ctx, AuditoriaZeta_ConsultarSalto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditoriaZetaServer is the server API for AuditoriaZeta service.
// All implementations must embed UnimplementedAuditoriaZetaServer
// for forward compatibility.
type AuditoriaZetaServer interface {
	// O Rails ou o Python consultam o estado da dobra
	ConsultarSalto(context.Context, *RequisicaoSalto) (*RespostaZeta, error)
	mustEmbedUnimplementedAuditoriaZetaServer()
}

// UnimplementedAuditoriaZetaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditoriaZetaServer struct{}

func (UnimplementedAuditoriaZetaServer) ConsultarSalto(context.Context, *RequisicaoSalto) (*RespostaZeta, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarSalto not implemented")
}
func (UnimplementedAuditoriaZetaServer) mustEmbedUnimplementedAuditoriaZetaServer() {}
func (UnimplementedAuditoriaZetaServer) testEmbeddedByValue()                       {}

// UnsafeAuditoriaZetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditoriaZetaServer will
// result in compilation errors.
type UnsafeAuditoriaZetaServer interface {
	mustEmbedUnimplementedAuditoriaZetaServer()
}

func RegisterAuditoriaZetaServer(s grpc.ServiceRegistrar, srv AuditoriaZetaServer) {
	// If the following call panics, it indicates UnimplementedAuditoriaZetaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditoriaZeta_ServiceDesc, srv)
}

func _AuditoriaZeta_ConsultarSalto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequisicaoSalto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditoriaZetaServer).ConsultarSalto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditoriaZeta_ConsultarSalto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditoriaZetaServer).ConsultarSalto(ctx, req.(*RequisicaoSalto))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditoriaZeta_ServiceDesc is the grpc.ServiceDesc for AuditoriaZeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditoriaZeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resonance.AuditoriaZeta",
	HandlerType: (*AuditoriaZetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarSalto",
			Handler:    _AuditoriaZeta_ConsultarSalto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resonance.proto",
}
