// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: resonance.proto

package resonance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequisicaoSalto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TokenOrto          string                 `protobuf:"bytes,1,opt,name=token_orto,json=tokenOrto,proto3" json:"token_orto,omitempty"` // O "Isso" (Posição 1 do Anel)
	TokenPara          string                 `protobuf:"bytes,2,opt,name=token_para,json=tokenPara,proto3" json:"token_para,omitempty"` // O "Aquilo" (Posição 4 do Anel)
	Eletronegatividade float32                `protobuf:"fixed32,3,opt,name=eletronegatividade,proto3" json:"eletronegatividade,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequisicaoSalto) Reset() {
	*x = RequisicaoSalto{}
	mi := &file_resonance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequisicaoSalto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequisicaoSalto) ProtoMessage() {}

func (x *RequisicaoSalto) ProtoReflect() protoreflect.Message {
	mi := &file_resonance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequisicaoSalto.ProtoReflect.Descriptor instead.
func (*RequisicaoSalto) Descriptor() ([]byte, []int) {
	return file_resonance_proto_rawDescGZIP(), []int{0}
}

func (x *RequisicaoSalto) GetTokenOrto() string {
	if x != nil {
		return x.TokenOrto
	}
	return ""
}

func (x *RequisicaoSalto) GetTokenPara() string {
	if x != nil {
		return x.TokenPara
	}
	return ""
}

func (x *RequisicaoSalto) GetEletronegatividade() float32 {
	if x != nil {
		return x.Eletronegatividade
	}
	return 0
}

type RespostaZeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbabilidadeZeta float32                `protobuf:"fixed32,1,opt,name=probabilidade_zeta,json=probabilidadeZeta,proto3" json:"probabilidade_zeta,omitempty"` // Proximidade do 0
	CurvaturaRicci    float32                `protobuf:"fixed32,2,opt,name=curvatura_ricci,json=curvaturaRicci,proto3" json:"curvatura_ricci,omitempty"`          // Tensão do espaço
	ResultadoFinal    float32                `protobuf:"fixed32,3,opt,name=resultado_final,json=resultadoFinal,proto3" json:"resultado_final,omitempty"`          // O "0" (Zeta Zero)
	ElementoLogico    string                 `protobuf:"bytes,4,opt,name=elemento_logico,json=elementoLogico,proto3" json:"elemento_logico,omitempty"`            // "Carbono Zeta"
	// Geometria Temporal e Spin
	SpinFase       float32   `protobuf:"fixed32,5,opt,name=spin_fase,json=spinFase,proto3" json:"spin_fase,omitempty"`                   // Orientação do elétron lógico
	Sh6Coeffs      []float32 `protobuf:"fixed32,6,rep,packed,name=sh6_coeffs,json=sh6Coeffs,proto3" json:"sh6_coeffs,omitempty"`         // Harmônicos de 6ª ordem (Anel)
	DensidadeTempo float32   `protobuf:"fixed32,7,opt,name=densidade_tempo,json=densidadeTempo,proto3" json:"densidade_tempo,omitempty"` // Convergência temporal
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RespostaZeta) Reset() {
	*x = RespostaZeta{}
	mi := &file_resonance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespostaZeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaZeta) ProtoMessage() {}

func (x *RespostaZeta) ProtoReflect() protoreflect.Message {
	mi := &file_resonance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaZeta.ProtoReflect.Descriptor instead.
func (*RespostaZeta) Descriptor() ([]byte, []int) {
	return file_resonance_proto_rawDescGZIP(), []int{1}
}

func (x *RespostaZeta) GetProbabilidadeZeta() float32 {
	if x != nil {
		return x.ProbabilidadeZeta
	}
	return 0
}

func (x *RespostaZeta) GetCurvaturaRicci() float32 {
	if x != nil {
		return x.CurvaturaRicci
	}
	return 0
}

func (x *RespostaZeta) GetResultadoFinal() float32 {
	if x != nil {
		return x.ResultadoFinal
	}
	return 0
}

func (x *RespostaZeta) GetElementoLogico() string {
	if x != nil {
		return x.ElementoLogico
	}
	return ""
}

func (x *RespostaZeta) GetSpinFase() float32 {
	if x != nil {
		return x.SpinFase
	}
	return 0
}

func (x *RespostaZeta) GetSh6Coeffs() []float32 {
	if x != nil {
		return x.Sh6Coeffs
	}
	return nil
}

func (x *RespostaZeta) GetDensidadeTempo() float32 {
	if x != nil {
		return x.DensidadeTempo
	}
	return 0
}

var File_resonance_proto protoreflect.FileDescriptor

const file_resonance_proto_rawDesc = "" +
	"\n" +
	"\x0fresonance.proto\x12\tresonance\"\x7f\n" +
	"\x0fRequisicaoSalto\x12\x1d\n" +
	"\n" +
	"token_orto\x18\x01 \x01(\tR\ttokenOrto\x12\x1d\n" +
	"\n" +
	"token_para\x18\x02 \x01(\tR\ttokenPara\x12.\n" +
	"\x12eletronegatividade\x18\x03 \x01(\x02R\x12eletronegatividade\"\x9d\x02\n" +
	"\fRespostaZeta\x12-\n" +
	"\x12probabilidade_zeta\x18\x01 \x01(\x02R\x11probabilidadeZeta\x12'\n" +
	"\x0fcurvatura_ricci\x18\x02 \x01(\x02R\x0ecurvaturaRicci\x12'\n" +
	"\x0fresultado_final\x18\x03 \x01(\x02R\x0eresultadoFinal\x12'\n" +
	"\x0felemento_logico\x18\x04 \x01(\tR\x0eelementoLogico\x12\x1b\n" +
	"\tspin_fase\x18\x05 \x01(\x02R\bspinFase\x12\x1d\n" +
	"\n" +
	"sh6_coeffs\x18\x06 \x03(\x02R\tsh6Coeffs\x12'\n" +
	"\x0fdensidade_tempo\x18\a \x01(\x02R\x0edensidadeTempo2X\n" +
	"\rAuditoriaZeta\x12G\n" +
	"\x0eConsultarSalto\x12\x1a.resonance.RequisicaoSalto\x1a\x17.resonance.RespostaZeta\"\x00B\x1eZ\x1cmanifold/transport/resonanceb\x06proto3"

var (
	file_resonance_proto_rawDescOnce sync.Once
	file_resonance_proto_rawDescData []byte
)

func file_resonance_proto_rawDescGZIP() []byte {
	file_resonance_proto_rawDescOnce.Do(func() {
		file_resonance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resonance_proto_rawDesc), len(file_resonance_proto_rawDesc)))
	})
	return file_resonance_proto_rawDescData
}

var file_resonance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resonance_proto_goTypes = []any{
	(*RequisicaoSalto)(nil), // 0: resonance.RequisicaoSalto
	(*RespostaZeta)(nil),    // 1: resonance.RespostaZeta
}
var file_resonance_proto_depIdxs = []int32{
	0, // 0: resonance.AuditoriaZeta.ConsultarSalto:input_type -> resonance.RequisicaoSalto
	1, // 1: resonance.AuditoriaZeta.ConsultarSalto:output_type -> resonance.RespostaZeta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resonance_proto_init() }
func file_resonance_proto_init() {
	if File_resonance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resonance_proto_rawDesc), len(file_resonance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resonance_proto_goTypes,
		DependencyIndexes: file_resonance_proto_depIdxs,
		MessageInfos:      file_resonance_proto_msgTypes,
	}.Build()
	File_resonance_proto = out.File
	file_resonance_proto_goTypes = nil
	file_resonance_proto_depIdxs = nil
}
